name: Build & Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:  # برای اجرای دستی

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ghcr.io/mokarian91/newelectron-php   # repository only, no tag
      IMAGE_TAG: 8.4-alpine
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Cache docker layers to speed up build
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          # build the 'base' stage with a proper single-tag
          docker build --progress=plain \
            --target base \
            -t $IMAGE_NAME:$IMAGE_TAG-base .
  
          # build the final image and tag with the version tag
          docker build --progress=plain \
            -t $IMAGE_NAME:$IMAGE_TAG .
  
          # also tag the versioned image as 'latest' if you want a :latest tag
          docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_NAME:latest
  
      - name: Push Docker image
        run: |
          docker push $IMAGE_NAME:$IMAGE_TAG-base
          docker push $IMAGE_NAME:$IMAGE_TAG
          docker push $IMAGE_NAME:latest
